[package]
name = "solana-secp256r1-program"
description = "Precompile implementation for the secp256r1 elliptic curve."
documentation = "https://docs.rs/solana-secp256r1"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
bytemuck = { workspace = true, features = ["derive"] }
solana-feature-set = { workspace = true }
solana-instruction = { workspace = true, features = ["std"] }
solana-precompile-error = { workspace = true }
solana-pubkey = { workspace = true }

[target.'cfg(all(not(target_arch = "wasm32"), not(target_os = "solana")))'.dependencies]
openssl = { workspace = true }

[dev-dependencies]
solana-logger = { workspace = true }
solana-sdk = { path = "../" }
solana-transaction-error = { workspace = true }

[features]
default = []
vendored = ["openssl/vendored"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
all-features = true
rustdoc-args = ["--cfg=docsrs"]

# This section is key for IDE support of test dependencies
[package.metadata.rust-analyzer]
# Ensures rust-analyzer loads cfg(test) code
all_targets = true
# Ensures proper completion and analysis of tests
all_features = true

[lints]
workspace = true
